Add risks of emblems as Deployment Considerations
felixlinker/draft-linker-digital-emblem pull request #1
Opened 2024-05-12 18:32 UTC by mstojens

2024-05-13 07:46 UTC, felixlinker requested changes

2024-05-13 07:46 UTC, felixlinker commented on draft-linker-digital-emblem.md
> +enable combatants to hold emblem-bearers accountable should misuse be detected.
I don't understand what this paragraph is trying to say. What do you want to say when pointing out the connection between covert inspection and the "observation of what behavior the emblem-bearing infrastructure has"?

2024-05-13 07:46 UTC, felixlinker commented on draft-linker-digital-emblem.md
> +out-of-band verification shows the emblem is invalidly applied" but... that's the truth, right?
For a document that has ICRC authors on it, we cannot talk about "attacks" for legal reasons. I think we should always use "asset X is [not] protected under IHL".

Besides that: What's the TODO here? Do you want to add a paragraph discussing this? If yes, I don't entirely understand what "this" is.

2024-05-13 07:46 UTC, felixlinker commented on draft-linker-digital-emblem.md
> +respect for IHL to preserve infrastructure that actively harms human rights (TODO: hrpc ref?).
This is supposed to referenced to the internet shutdown discussions, right?

2024-05-13 07:46 UTC, felixlinker commented on draft-linker-digital-emblem.md
> +This would be a misuse of respect for IHL to reduce the vendor's risk of cyberattack, to its profit.
Isn't this a straight-forward attack by negating req. authentic? If yes, it might be worth generalizing this paragraph to discuss the inherent risks of our trust model: People can always claim bullshit, but we try to get them through accountability.

2024-05-21 08:23 UTC, felixlinker commented
Hi @mstojens! I did a rewrite of your changes. I tried to end it on a more positive note. Let me know what you think of my changes. I think, my language is a bit less IETF-style than yours (I talk less about deployers, vencors, etc.). This is maybe not ideal. But it's hard for me to talk this language! Anyways. Let me know what you think!

2024-05-21 09:23 UTC, felixlinker approved these changes

2024-05-23 16:40 UTC, mstojens commented
I do like it. I pinged some folks offline who are interested, so I'd give it to next week if that's ok to see if anyone else wants to weigh in.

2024-05-29 07:49 UTC, felixlinker commented
@mstojens Seems like there are no objections. I will merge unless you object! :)

2024-05-29 16:38 UTC, mstojens commented
Go for it; further contributions can be handled in a new PR if they come up.

2024-05-29 17:15 UTC, merged